### ISSUE TITLE
"validate is not a function" after npm install, npm start

### ISSUE THREAD

**Issue by macbem** [survivejs/react-boilerplate#4]
I've tried two times, I have the files cloned from this repository. Here's the debug log

`0 info it worked if it ends with ok

1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]

2 info using npm@2.15.8

3 info using node@v4.4.7

4 verbose run-script [ 'prestart', 'start', 'poststart' ]

5 info prestart react-boilerplate@2.5.6

6 info start react-boilerplate@2.5.6

7 verbose unsafe-perm in lifecycle true

8 info react-boilerplate@2.5.6 Failed to exec start script

9 verbose stack Error: react-boilerplate@2.5.6 start: `webpack-dev-server`

9 verbose stack Exit status 1

9 verbose stack     at EventEmitter.<anonymous> 
(/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)

9 verbose stack     at EventEmitter.emit (events.js:172:7)

9 verbose stack     at ChildProcess.<anonymous>(/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)

9 verbose stack     at ChildProcess.emit (events.js:172:7)

9 verbose stack     at maybeClose (internal/child_process.js:827:16)

9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

10 verbose pkgid react-boilerplate@2.5.6

11 verbose cwd /Users/macbem/Documents/react-practice/kanban-app

12 error Darwin 15.6.0

13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"

14 error node v4.4.7

15 error npm  v2.15.8

16 error code ELIFECYCLE

17 error react-boilerplate@2.5.6 start: `webpack-dev-server`
17 error Exit status 1

18 error Failed at the react-boilerplate@2.5.6 start script 'webpack-dev-server'.

18 error This is most likely a problem with the react-boilerplate package,

18 error not with npm itself.

18 error Tell the author that this fails on your system:

18 error     webpack-dev-server

18 error You can get information on how to open an issue for this project with:

18 error     npm bugs react-boilerplate

18 error Or if that isn't available, you can get their info via:

18 error

18 error     npm owner ls react-boilerplate

18 error There is likely additional logging output above.

19 verbose exit [ 1, true ]
`

**Comment by bebraw** [comment]
Hi,

Can you fix `webpack-validator` version to `2.2.3`? There was a minor regression at `2.2.4` (released hour ago). We'll get this fixed asap.

**Comment by macbem** [comment]
Thanks, it worked.

**Comment by bebraw** [comment]
Fixed in https://github.com/js-dxtools/webpack-validator/pull/120 .

So `npm install` against the original project should work again.
